name: Deploy to Google App Engine

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: flask-service
  REGION: us-west1

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          version: '342.0.0'
          service_account_key: ${{ secrets.GCP_SA_KEY }}  # Use the secret for your service account key

      - name: Deploy to Google App Engine
        run: |
          gcloud app deploy --quiet --project=${{ env.PROJECT_ID }}

      - name: View deployment logs
        run: gcloud app logs tail -s ${{ env.SERVICE_NAME }}
